version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - loanbroker
      - bank1
      - bank2
      - bank3
      - bank4
      - creditbureau
    networks:
      - backend

  loanbroker:
    image: lennard2001/loanbroker:lennard2001
    build:
      context: ./loan-broker
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      SPRING_ACTIVEMQ_USER: admin
      SPRING_ACTIVEMQ_PASSWORD: admin
    depends_on:
      - activemq
      - creditbureau
    networks:
      - backend

  bank1:
    image: lennard2001/bank1:lennard2001
    build:
      context: ./bank1
      dockerfile: dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      SPRING_ACTIVEMQ_USER: admin
      SPRING_ACTIVEMQ_PASSWORD: admin
    depends_on:
      - activemq
    networks:
      - backend

  bank2:
    image: lennard2001/bank2:lennard2001
    build:
      context: ./bank2
      dockerfile: dockerfile
    ports:
      - "8083:8083"
    environment:
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      SPRING_ACTIVEMQ_USER: admin
      SPRING_ACTIVEMQ_PASSWORD: admin
    depends_on:
      - activemq
    networks:
      - backend

  bank3:
    image: lennard2001/bank3:lennard2001
    build:
      context: ./bank3
      dockerfile: dockerfile
    ports:
      - "8084:8084"
    environment:
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      SPRING_ACTIVEMQ_USER: admin
      SPRING_ACTIVEMQ_PASSWORD: admin
    depends_on:
      - activemq
    networks:
      - backend

  bank4:
    image: lennard2001/bank4:lennard2001
    build:
      context: ./bank4
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      SPRING_ACTIVEMQ_USER: admin
      SPRING_ACTIVEMQ_PASSWORD: admin
    depends_on:
      - activemq
    networks:
      - backend

  creditbureau:
    image: lennard2001/creditbureau:lennard2001
    build:
      context: ./creditbureau
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - backend

  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASSWORD: admin
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 2048
    networks:
      - backend

networks:
  backend:
    driver: bridge