apiVersion: apps/v1
kind: Deployment
metadata:
  name: loanbroker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loanbroker
  template:
    metadata:
      labels:
        app: loanbroker
    spec:
      containers:
      - name: loanbroker
        image: lennard2001/loanbroker:lennard2001
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_ACTIVEMQ_BROKER_URL
          value: tcp://activemq-service:61616
        - name: SPRING_ACTIVEMQ_USER
          value: admin
        - name: SPRING_ACTIVEMQ_PASSWORD
          value: admin
        - name: CREDIT_BUREAU_URL
          value: http://creditbureau-service:8081
---
apiVersion: v1
kind: Service
metadata:
  name: loanbroker-service
spec:
  selector:
    app: loanbroker
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30090
  type: NodePort
